server:
  port: 8890

spring:
  datasoruce:
    url: jdbc:mysql://127.0.0.1:3306/eesy?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
